name: Build Docker Image

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build containers
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm,linux/amd64,linux/arm64/v8
        tags: goaccess-static
